### PR TITLE
updated theme to reflect recent code update to article node

### PR DESCRIPTION
**Pull request by ben2collins**
@drogers98 Updated the hc_article node with new Publish date field. 
Unlike the original field this field gets its value(timestamp) from the node's  from default "Published" field

### CODE REVIEW

**Comment by drogers98** [comment]
@ben2collins so is that custom field to be removed then? Likely would mean:

- Need to write an update script to remove the field
- Config needs to be updated
- Potentially views/etc that use that field for ordering need to be updated.

Please advise the desire around changing this field so we can address the above.

**Comment by ben2collins** [comment]
@drogers98  I want to change the field because the Article node still refuses to update  even after I moved my update function from the .install file to the .module file. Since the module never pushed an update I figured it be a lot simpler to create a published date field that wouldn't require a DB update.

**Comment by drogers98** [comment]
So, that approach could work, changing from custom field to stock field. The thing to remember though is, that field was added for a reason in the first place, in order to be able to easily set a date "that was the date of the publication" not "the date it was added to drupal".

If the web services team wants this change we can do it, but I caution that it will potentially have adverse affects on existing sites, ie them now switching to a date they never manually set.

What exactly were you trying to update on hc_article? perhaps that is the easier question to ask first. Happy to help troubleshoot the update script if it makes more sense than completely changing fields.

**Comment by ben2collins** [comment]
I added a new published date field to the Config 
and I wanted to update the Article node with this new field.

**Comment by ben2collins** [comment]
@drogers98 Is it possible to get this update merged sometime today?

**Pull request closed without merging**
